### ISSUE TITLE
iOS - Epic - Mark a task as done

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#244]
Add functionality to the app that marks a task as complete.

- [ ] Add a "Done" button to a task on the Details/Add/Edit screen to mark a task as complete
- [ ] Add a "done" property to the task that can be true or false
- [ ] On the List Screen, do not display tasks that are done
- [ ] Add a new "Done Tasks" Screen that displays tasks that are done
- [ ] Add navigation to the "Done Tasks" Screen from the "List Screen"
